//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.Letters = new HashSet<Letter>();
            this.IssueLetters = new HashSet<IssueLetter>();
            this.Bills = new HashSet<Bill>();
        }
    
        public int IssueId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<Letter> Letters { get; set; }
        public virtual ICollection<IssueLetter> IssueLetters { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
