//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueLetter
    {
        public int IssueLetterId { get; set; }
        public int IssueId { get; set; }
        public int LetterId { get; set; }
    
        public virtual Letter Letter { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
