//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public Letter()
        {
            this.IssueLetters = new HashSet<IssueLetter>();
        }
    
        public int LetterId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Body { get; set; }
        public bool Against { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Slug { get; set; }
    
        public virtual ICollection<IssueLetter> IssueLetters { get; set; }
    }
}
