//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateDateUtc { get; set; }
        public string Ip { get; set; }
        public string UserAgent { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public int OrderStatusId { get; set; }
        public string Name { get; set; }
        public string AddressLineOne { get; set; }
        public string AddressLineTwo { get; set; }
        public string CityStateZip { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string StripeChargeId { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }
    }
}
