//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int PersonId { get; set; }
        public string OpenCongressId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string FullNameAndTitle { get; set; }
        public Nullable<int> Session { get; set; }
        public string State { get; set; }
        public Nullable<int> District { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Party { get; set; }
        public bool Active { get; set; }
        public string MailingAddressOne { get; set; }
        public string MailingCity { get; set; }
        public string MailingZip { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateUtc { get; set; }
        public string MailingState { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
