//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteCongress.OpenCongressImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string MiddleInital { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> TotalVotes { get; set; }
        public string Gender { get; set; }
        public string CongressOffice { get; set; }
        public Nullable<double> UserApproval { get; set; }
        public string YoutubeId { get; set; }
        public string URL { get; set; }
        public Nullable<int> VotesRepublican { get; set; }
        public Nullable<int> VotesDemocratic { get; set; }
        public string Email { get; set; }
        public Nullable<int> Session { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
